

mod_id=nologpunch
curse_slug=no-log-punch
curse_id=463775
mod_version=2.0.1
mod_name=nologpunch
mod_group_id=com.lothrazar.nologpunch
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
modrinth_id=

flib_version=0.1.0
flib_file=8022223


